export const GAME_CONFIG = {
  SQUARE_SIZE: 500,
  CIRCLE_SIZE: 40,
  MIN_DISTANCE: 5,
  FADE_DURATION: 3000,
  AUTO_PLAY_DELAY: 2000,
  AUTO_PLAY_INTERVAL: 500,
  TIMER_INTERVAL: 100,
  TOP_ROWS: 3,
  DEFAULT_POINTS: 5, 
  MIN_POINTS: 1,
  MAX_POINTS: 20000,
};

export const GAME_STATUS = {
  READY: "ready",
  PLAYING: "playing",
  CLEARED: "cleared",
  OVER: "over"
}; 